name: Sync Garmin Global to CN

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

env:
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}
  GARMIN_GLOBAL_OAUTH1: ${{ secrets.GARMIN_GLOBAL_OAUTH1 }}
  GARMIN_GLOBAL_OAUTH2: ${{ secrets.GARMIN_GLOBAL_OAUTH2 }}
  GH_PAT: ${{ secrets.GH_PAT }}
  GARMIN_SYNC_NUM: "10"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sync Garmin Global to Garmin CN
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - run: yarn

      - name: Run Sync
        run: yarn sync_global
        timeout-minutes: 10

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Save Garmin Session
          skip_dirty_check: false
